name: Build

on:
  push:
    branches:
      - main
      - develop

jobs:
  test:
    uses: ./.github/workflows/test.yml

  dependency-check:
    uses: ./.github/workflows/dependency_check.yml

  coverage:
    needs:
      - test
      - dependency-check
    uses: ./.github/workflows/coverage.yml

  deploy-docker:
    needs: coverage
    uses: ./.github/workflows/deploy_docker.yml
    secrets:
      username: ${{ secrets.DOCKER_HUB_USERNAME }}
      app_name: ${{ secrets.DOCKER_HUB_APP_NAME }}
      token: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}