name: Test

on:
  workflow_call:

jobs:
  test:
    name: Test
#    strategy:
#      matrix:
#        go-version: [ 1.19 ]
#        platform: [ windows-latest, macos-latest, ubuntu-latest ]
#    runs-on: ${{ matrix.platform }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Test with Maven
        run: mvn test -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn